/** Public references checked 2026-09-16. Interpretation is separate from measured data. */
export const PAPERS = [
  { id: 'hertzmann', year: '1998 · SIGGRAPH · pp. 453–460', authors: 'Aaron Hertzmann', title: 'Painterly Rendering with Curved Brush Strokes of Multiple Sizes', url: 'https://mrl.cs.nyu.edu/publications/painterly98/', pdf: 'https://mrl.cs.nyu.edu/publications/painterly98/hertzmann-siggraph98.pdf', doi: '10.1145/280814.280951',
    principle: '以不同大小的曲线笔刷分层绘制。每层使用相应尺度的模糊参考图，在误差显著处放笔；曲线沿梯度的垂直方向延伸。同层笔触随机排列，以减弱机械规律。第 3 节把笔宽、曲率、透明度与颜色扰动组织为可调风格参数。',
    relation: '早期曲线实现借鉴分层、模糊、误差定位与梯度方向。方案 A 保留由粗到细的思想，改用固定预算、胶囊笔刷和逐行扫描；六种自由笔刷借鉴参数化表达的思路。',
    boundary: '论文没有给出本项目六位画家的参数表。当前算法不使用其完整曲线生成流程，五遍比例与扫描规则也是本项目的设定。' },
  { id: 'huang', year: '2019 · ICCV · pp. 8709–8718', authors: 'Zhewei Huang, Wen Heng, Shuchang Zhou', title: 'Learning to Paint With Model-Based Deep Reinforcement Learning', url: 'https://openaccess.thecvf.com/content_ICCV_2019/html/Huang_Learning_to_Paint_With_Model-Based_Deep_Reinforcement_Learning_ICCV_2019_paper.html', pdf: 'https://arxiv.org/abs/1903.04411', doi: '10.1109/ICCV.2019.00880',
    principle: '神经渲染器参与基于模型的强化学习，策略输出笔触位置、形状、颜色与透明度，考虑连续绘制的长期收益。训练不要求人类画家的逐笔轨迹。',
    relation: '提供“把图像重建看成连续笔触决策”的参照。本项目同样保存可回放的笔触序列，但每一步使用显式误差搜索。',
    boundary: '没有运行这篇论文的策略网络或神经渲染器；当前贪心搜索只接受当步误差改善，不具备学习到的长期规划能力。' },
  { id: 'zou', year: '2021 · CVPR · pp. 15689–15698', authors: 'Zhengxia Zou, Tianyang Shi, Shuang Qiu, Yi Yuan, Zhenwei Shi', title: 'Stylized Neural Painting', url: 'https://openaccess.thecvf.com/content/CVPR2021/html/Zou_Stylized_Neural_Painting_CVPR_2021_paper.html', pdf: 'https://openaccess.thecvf.com/content/CVPR2021/papers/Zou_Stylized_Neural_Painting_CVPR_2021_paper.pdf', doi: '10.1109/CVPR46437.2021.01543',
    principle: '用神经渲染器近似绘制过程，通过优化笔触参数逼近目标；分离形状与着色，并用最优传输相关方法处理参数优化中的零梯度问题。',
    relation: '“参数 → 渲染 → 图像误差 → 改善参数”的反馈结构是本项目的研究参照。项目用解析颜色拟合，加上随机候选和局部搜索，换取浏览器端可执行的实现。',
    boundary: '当前没有反向传播、神经渲染器或最优传输损失。最小二乘拟色由当前混合模型推导，不能当作该论文算法的直接移植。' },
  { id: 'hu', year: '2023 · ACM Multimedia', authors: 'Teng Hu, Ran Yi, Haokun Zhu, Liang Liu, Jinlong Peng, Yabiao Wang, Chengjie Wang, Lizhuang Ma', title: 'Stroke-based Neural Painting and Stylization with Dynamically Predicted Painting Region', url: 'https://arxiv.org/abs/2309.03504', pdf: 'https://arxiv.org/html/2309.03504v2', doi: '10.1145/3581783.3611766',
    principle: '先预测画在哪里，再预测画什么：compositor 决定区域，painter 决定笔触。论文讨论独立均匀分块导致的接缝，并通过动态区域规划处理。',
    relation: '帮助区分“区域顺序”与“区域内笔触”。方案 A 使用可解释的固定扫描顺序；整条笔触在共享画布上拟合，允许覆盖网格边界。',
    boundary: '没有部署动态区域网络或语义识别；允许跨边界只减少硬裁剪问题，不保证消除全部区域痕迹，也不等价于论文方法。' },
] as const;

export const STYLE_EVIDENCE = [
  { id: 'monet', source: 'National Gallery · Claude Monet, The Water-Lily Pond (1899)', url: 'https://www.nationalgallery.org.uk/paintings/claude-monet-the-water-lily-pond',
    observation: '馆藏解读记录并置的厚笔触、柳树与倒影中的长竖笔，以及水面碎笔。它也对比了莫奈其他时期更柔和、混合的画法。',
    feeling: '本项目提取“轻扫、片段、光色跳动”的感受，选择短段两端收细；这是对部分作品特征的转译。',
    rationale: '基础宽度 6，分段目标 3，让同一手势呈现多次收放；roughness 0.1 对应每轴至多约 0.25px 扰动，保持轻柔。',
    limit: '莫奈并非只画短笔触。分成 3 段、渐细曲线及具体像素值都是人工设定，未由画作测量得到。' },
  { id: 'vangogh', source: 'Van Gogh Museum · Unravel Van Gogh: Thick brushstrokes', url: 'https://ontrafel.vangogh.nl/en/story/29/thick-brushstrokes/',
    observation: '博物馆通过侧光展示厚笔迹和前景植物处堆积的颜料，强调同一画面中笔触的多样性。',
    feeling: '提取“饱满、用力、可见的笔迹”，用中段鼓起与重叠笔层表达厚实感。',
    rationale: '基础宽度 8，bulge 系数 0.7 使中段达到 1.7 倍基础宽度；roughness 0.3 对应至多约 0.75px 扰动。第二层半宽、透明度乘 0.6，产生叠涂差异。',
    limit: '二维重叠不模拟真实颜料高度、侧光阴影或湿颜料混合；旋转线条由用户手势产生，参数不是梵高笔迹的统计值。' },
  { id: 'gauguin', source: 'National Gallery · Paul Gauguin, Harvest: Le Pouldu (1890)', url: 'https://www.nationalgallery.org.uk/paintings/paul-gauguin-harvest-le-pouldu',
    observation: '馆藏解读将清晰界定的形态与平坦色域联系到高更的综合主义画风。',
    feeling: '提取“平整、稳定、装饰性色块”的感受，优先让一笔铺色均匀。',
    rationale: '基础宽度 10，uniform 系数 0.15 使宽度仅约 ±2.25% 波动；roughness 0.05 对应至多约 0.125px 扰动，使用单层连续笔迹。',
    limit: '均匀画笔不能自动生成综合主义构图、黑色边线或色域。10px 与 0.15 是相对其他预设的设计取舍，不是实测。' },
  { id: 'rembrandt', source: 'National Gallery · Rembrandt: The Late Works, What is paint?', url: 'https://www.nationalgallery.org.uk/learning/teachers-notes/rembrandt-the-late-works-a-resource-for-science-teachers?viewPage=3',
    observation: '资料通过《63岁自画像》说明伦勃朗厚涂区域的可见笔迹与颜料物性。它支持丰富表面肌理这一方向。',
    feeling: '项目将“触感、阻力、提按”转成压感宽度与干笔缺口，作为可体验的肌理选项。',
    rationale: '基础宽度 5，压力映射到 0.3–1 倍基础宽度，再附加约 ±6% 波动；roughness 0.4 对应至多约 1px 扰动。dry 随机略过 15% 的小线段。',
    limit: '厚涂资料不能直接推出干笔缺口率15%。这里是较宽泛的肌理联想，没有复现厚涂高光、罩染或明暗法；这些数值有待独立风格验证。' },
  { id: 'picasso', source: 'The Met · Pablo Picasso (1881–1973)', url: 'https://www.metmuseum.org/essays/pablo-picasso-1881-1973',
    observation: '馆方文章讨论分析立体主义中形体的分解，以及综合立体主义中的拼贴与材质。依据主要在形体组织层面。',
    feeling: '项目把“分解、间断、节奏”的感受转译为断续笔迹，是六种映射中证据较弱的一种形式联想。',
    rationale: '基础宽度 5，uniform 系数 0.3 产生约 ±4.5% 波动；分段目标 2，roughness 0.2 对应至多约 0.5px 扰动；每7个小线段中的指定一段留空。',
    limit: '没有证据表明毕加索按这个周期断笔。它不模拟多视点或立体主义构图，不应称作对毕加索笔触统计规律的复现。' },
  { id: 'sargent', source: 'Silvia Centeno & Dorothy Mahon (2005) · A Technical Study of John Singer Sargent’s Portrait of Madame Pierre Gautreau · Metropolitan Museum Journal 40', url: 'https://www.metmuseum.org/met-publications/technical-study-sargents-madame-pierre-gautreau-the-metropolitan-museum-journal-v-40-2005',
    observation: '该技术研究在背景细节中分析松散而有表现力的笔迹与半不透明薄擦层，见文中 Figure 12、印刷页127。',
    feeling: '项目选取“流畅、概括、轻盈收放”的感受，让一段手势尽量连续，起收笔较细。',
    rationale: '基础宽度 7，taper 使两端为基础宽度的0.3倍、中间为1倍；单段、smooth、roughness 0.05 降低路径扰动。',
    limit: '资料并未给出这条渐细函数。当前也不模拟薄擦层的材料结构或水彩渗化，单一预设不能代表萨金特不同时期与媒介。' },
] as const;
