import { chromium } from '@playwright/test';
import assert from 'node:assert/strict';
import { mkdirSync } from 'node:fs';
const out = '论文/产品介绍与浮动面板验收';
mkdirSync(out, { recursive: true });
const browser = await chromium.launch();
try {
  const page = await browser.newPage({ viewport: { width: 1440, height: 1000 } });
  page.setDefaultTimeout(20000);
  const errors = []; page.on('pageerror', e => errors.push(e.message));
  await page.goto('http://localhost:3001/');
  const cta = page.getByRole('button', { name: '开始我的第一幅画' });
  assert.ok((await cta.boundingBox()).height >= 90);
  assert.equal(await page.locator('#home-more').getAttribute('open'), null);
  assert.equal(await page.locator('#how-it-works').isVisible(), false);
  await page.waitForTimeout(800);
  await page.screenshot({ path: out + '/首页默认收起.png', fullPage: true });
  await page.locator('#home-more summary').click();
  assert.equal(await page.locator('#how-it-works').isVisible(), true);
  await page.locator('#home-more summary').click();
  assert.equal(await page.locator('#how-it-works').isVisible(), false);
  await page.goto('http://localhost:3001/intro');
  await page.getByRole('button', { name: '收起介绍目录' }).waitFor();
  await page.screenshot({ path: out + '/产品介绍桌面.png' });
  assert.equal(await page.getByRole('button', { name: '浏览产品全貌' }).count(), 0);
  assert.equal(await page.locator('.intro-section').count(), 10);
  await page.locator('#intro-toc a[href="#styles"]').click();
  await page.getByRole('button', { name: /梵高.*鼓起厚涂/ }).click();
  await page.screenshot({ path: out + '/六种笔刷.png' });
  await page.locator('#intro-toc a[href="#algorithm"]').click();
  await page.getByRole('button', { name: '运行笔触演示' }).click();
  const slider = page.getByRole('slider', { name: /预览笔数/ });
  await slider.waitFor({ timeout: 60000 });
  const count = Number(await slider.getAttribute('max')); assert.ok(count > 0 && count <= 1000);
  const rendered = await page.getByRole('img', { name: '笔触算法实际重建结果' }).evaluate(c => c.toDataURL());
  await slider.fill('0');
  assert.notEqual(await page.getByRole('img', { name: '笔触算法实际重建结果' }).evaluate(c => c.toDataURL()), rendered);
  await slider.fill(String(count));
  await page.locator('.intro-demo').filter({ has: slider }).screenshot({ path: out + '/真实算法演示.png' });
  await page.getByRole('button', { name: 'B · 笔触引导', exact: true }).click();
  await page.getByRole('heading', { name: '按同一套计划接收逐笔提示' }).waitFor();
  await page.setViewportSize({ width: 390, height: 844 });
  await page.getByRole('button', { name: '收起介绍目录' }).click();
  await page.getByRole('button', { name: '展开介绍目录' }).click();
  await page.locator('#intro-toc a[href="#overview"]').click();
  assert.equal(await page.locator('#intro-toc').count(), 0);
  assert.equal(await page.evaluate(() => document.documentElement.scrollWidth > innerWidth), false);
  await page.screenshot({ path: out + '/产品介绍手机.png' });
  await page.setViewportSize({ width: 1440, height: 1000 });
  await page.evaluate(() => {
    const c = document.createElement('canvas'); c.width = c.height = 128;
    const ctx = c.getContext('2d'); ctx.fillStyle = 'white'; ctx.fillRect(0, 0, 128, 128); ctx.fillStyle = '#69D2C2'; ctx.fillRect(24, 24, 80, 80);
    sessionStorage.setItem('star-bindpaint-source', c.toDataURL()); sessionStorage.removeItem('star-bindpaint-free-style'); localStorage.removeItem('startrace-companion-position-v1');
  });
  await page.goto('http://localhost:3001/paint');
  await page.getByRole('button', { name: '完整', exact: true }).waitFor({ timeout: 60000 });
  const panel = page.getByTestId('floating-companion');
  const drag = async (locator, dx, dy) => { const box = await locator.boundingBox(); await page.mouse.move(box.x + box.width / 2, box.y + box.height / 2); await page.mouse.down(); await page.mouse.move(box.x + box.width / 2 + dx, box.y + box.height / 2 + dy, { steps: 12 }); await page.mouse.up(); };
  await page.getByRole('button', { name: '解锁月亮伙伴位置' }).click();
  const initial = await panel.boundingBox();
  const canvasBefore = await page.locator('canvas.paint-canvas').evaluate(c => c.toDataURL());
  await drag(page.getByRole('button', { name: '移动月亮伙伴' }), -300, 100);
  const moved = await panel.boundingBox(); assert.ok(moved.x < initial.x - 250);
  assert.equal(await page.locator('canvas.paint-canvas').evaluate(c => c.toDataURL()), canvasBefore);
  await page.getByRole('button', { name: '锁定月亮伙伴位置' }).click();
  await drag(page.getByRole('button', { name: '移动月亮伙伴' }), -100, 50);
  assert.equal((await panel.boundingBox()).x, moved.x);
  await page.screenshot({ path: out + '/提示卡移动后锁定.png' });
  await page.getByRole('button', { name: '收起月亮伙伴', exact: true }).click();
  assert.ok((await panel.boundingBox()).width <= 60);
  await page.getByRole('button', { name: '展开月亮伙伴' }).click();
  await page.setViewportSize({ width: 390, height: 844 });
  await page.waitForTimeout(150);
  const mobile = await panel.boundingBox(); assert.ok(mobile.x >= 8 && mobile.x + mobile.width <= 383);
  await page.getByRole('button', { name: '解锁月亮伙伴位置' }).click();
  await page.getByRole('button', { name: '收起月亮伙伴', exact: true }).click();
  await drag(page.getByRole('button', { name: '展开月亮伙伴' }), -100, 90);
  assert.ok((await panel.boundingBox()).width <= 60);
  await page.screenshot({ path: out + '/手机方圆图标.png' });
  await page.getByRole('button', { name: '展开月亮伙伴' }).click();
  const stored = await page.evaluate(() => JSON.parse(localStorage.getItem('startrace-companion-position-v1')));
  assert.equal(stored.locked, false);
  await page.reload();
  await page.getByRole('button', { name: '锁定月亮伙伴位置' }).waitFor();
  assert.equal(await page.evaluate(() => document.documentElement.scrollWidth > innerWidth), false);
  assert.deepEqual(errors, []);
  console.log('PASS: 首页折叠、10章目录、真实算法/笔刷/实验演示、面板拖动锁定收缩与移动端边界');
} finally { await browser.close(); }
